# -*- coding: utf-8 -*-
"""AgentFlow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-CMiIif0UC9M4Al26piN4Ade_v47iyGs
"""

!pip install -U ddgs crewai

import os
from crewai import Agent, Task, Crew, Process, LLM
from crewai.tools import tool
from ddgs import DDGS

# ==========================================
# 1. KONFIGURACJA MODELU I NARZĘDZIA
# ==========================================
MOJ_KLUCZ_API = ""
os.environ["GEMINI_API_KEY"] = MOJ_KLUCZ_API

zaawansowany_llm = LLM(
    model="gemini/gemini-2.5-flash",
    api_key=MOJ_KLUCZ_API
)

@tool("Przeszukiwanie Internetu")
def wyszukiwarka(zapytanie: str) -> str:
    """Wyszukiwanie informacji w internecie."""
    try:
        wyniki = list(DDGS().text(zapytanie, max_results=4))
        if not wyniki:
            return "Puste wyniki. Użyj ogólniejszego lub angielskiego hasła."
        return str(wyniki)
    except Exception as e:
        return f"Błąd: {str(e)}"

# ==========================================
# 2. TWORZENIE AGENTÓW (Bez zmian, ale zezwalamy na delegowanie!)
# ==========================================

# UWAGA: Zmieniamy allow_delegation na True, żeby Menedżer mógł im zlecać zadania!
badacz_internetu = Agent(
    role='Główny Badacz Internetu',
    goal='Wyszukiwanie prawdziwych informacji w sieci',
    backstory='Jesteś mistrzem wyszukiwania. Zawsze sprawdzasz fakty w internecie.',
    verbose=True,
    tools=[wyszukiwarka],
    allow_delegation=True, # <--- ZMIANA
    llm=zaawansowany_llm
)

analityk_danych = Agent(
    role='Analityk Rynku',
    goal='Analiza danych z internetu i wyciąganie wniosków',
    backstory='Bezbłędnie wyłapujesz trendy z dostarczonych tekstów.',
    verbose=True,
    allow_delegation=True, # <--- ZMIANA
    llm=zaawansowany_llm
)

redaktor = Agent(
    role='Dyrektor ds. Raportowania',
    goal='Stworzenie raportu końcowego w formacie Markdown',
    backstory='Ubierasz analizy w piękne, ustrukturyzowane raporty.',
    verbose=True,
    allow_delegation=True, # <--- ZMIANA
    llm=zaawansowany_llm
)

# ==========================================
# 3. ZADANIA I NOWY ZESPÓŁ HIERARCHICZNY
# ==========================================

TEMAT_BADANIA = "Potencjał AI w gospodarce odpadami" # Dałem po angielsku dla lepszych wyników!

# W trybie hierarchicznym zadania mogą być bardziej ogólne, Menedżer sam zadba o szczegóły.
zadanie_glowne = Task(
    description=f'Przeprowadź kompleksowe badanie na temat: {TEMAT_BADANIA}. Przeszukaj internet, zidentyfikuj kluczowe trendy i firmy, a następnie stwórz z tego profesjonalny raport w języku polskim.',
    expected_output='Kompleksowy raport w Markdown w języku polskim.',
    # Nie przypisujemy z góry agenta! Menedżer zdecyduje, komu to dać.
)

# TWORZYMY ZESPÓŁ Z MENEDŻEREM
agencja_hierarchiczna = Crew(
    agents=[badacz_internetu, analityk_danych, redaktor],
    tasks=[zadanie_glowne],
    process=Process.hierarchical, # <--- MAGIA DZIEJE SIĘ TUTAJ
    manager_llm=zaawansowany_llm, # <--- POWOŁUJEMY MENEDŻERA
    verbose=True
)

print(f"Rozpoczynam misję pod nadzorem Menedżera: {TEMAT_BADANIA}\n")
wynik_koncowy = agencja_hierarchiczna.kickoff()

print("\n" + "="*60)
print("🚀 RAPORT ZATWIERDZONY PRZEZ MENEDŻERA:")
print("="*60 + "\n")
print(wynik_koncowy)

# Ten skrypt stworzy czysty plik requirements.txt z paczkami niezbędnymi dla naszych agentów
zawartosc = """crewai
ddgs
"""

with open('requirements.txt', 'w') as f:
    f.write(zawartosc)

print("✅ Plik requirements.txt został utworzony!")